### ISSUE TITLE
Class Autoloader Throws Exceptions

### ISSUE THREAD

**Issue by CBeerta** [mikecao/flight#1]
The Class Autoloader in Flight throws an exception if it can't find anything. If you have multiple autoloaders this will break things, as none of the possible autoloaders to follow will be executed.

This for example makes using Twig with Flight impossible.

**Comment by mikecao** [comment]
Fixed in commit e1cf8a1f997b94c0a135. Flight will now only throw an exception if it is the very last autoloader to run.
