### ISSUE TITLE
Syntax examples for class/method

### ISSUE THREAD

**Issue by gmoisio** [mikecao/flight#100]
Hi, is it possible to have syntax examples for class/method, rather than anonymous function for:

1) Named Parameters

``` php
Flight::route('/@name/@id', function($name, $id){
    echo "hello, $name ($id)!";
});
```

2) Route Info

``` php
Flight::route('/', function($route){
    $route->methods;
    $route->params;
    $route->regex;
    $route->splat;
});
```

3) Filter

``` php
Flight::before('start', function(&$params, &$output){
    // Do something
});
```

Thanks

**Comment by kafene** [comment]
http://www.php.net/manual/en/language.types.callable.php

**Comment by gmoisio** [comment]
Looking at the link I can understand how to pass class/method:

``` php
Flight::route('/@name/@id', array('class', 'method'));
```

But how to pass the additional parameters such as the examples for anonymous functions?
Thanks

**Comment by mikecao** [comment]
Those variables are passed to your class method the same as an anonymous function.

```
$class->method($name, $id)
```

**Comment by gmoisio** [comment]
You mean

``` php
Flight::route('/@name/@id', $class->method($name, $id));
```

So it's necessary to instanciate the class... it's different from

``` php
Flight::route('/@name/@id', array('class', 'method'));
```

**Comment by kafene** [comment]
When you use the router, you are not passing anything. Things are being passed to you.

Try this:

```
class what {
    function happened() {
        var_dump(func_get_args());
    }
    function is_up($frogs) {
        var_dump(func_get_args());
    }
}
```

``` php
    Flight::route('/@name/@id', array(new what(), 'happened'));
    Flight::route('/@lol/@foo/@bar', array(new what(), 'is_up'));
```

**Comment by mikecao** [comment]
@gmcms Your callable can either be static, `array('class','method')` or an instance, `array($class,'method)`. Flight will simply pass the parameters along. So your method definition needs to use those parameters.

``` php
class myclass {
  function mymethod($name, $id) {
    // Do something
  }
}
```

**Comment by gmoisio** [comment]
Nice, I understand....
