### ISSUE TITLE
$_SESSION vs Flight internal variables storage

### ISSUE THREAD

**Issue by gmoisio** [mikecao/flight#101]
Hi, what is the best choice to store informations such as user login informations (lang, isLogged, ...)?
If I understood, internal storage could have the same usage as $_SESSION except that all the values are lost as soon as we close the browser tab (not the full browser).
Thanks

**Comment by mikecao** [comment]
Flight variables only last the length of the HTTP request. It has nothing to do with the browser.

**Comment by gmoisio** [comment]
Is it what we call flash in some other frameworks?

**Comment by mikecao** [comment]
No, a flash message uses cookies. Flight variables are simply in memory.

**Comment by gmoisio** [comment]
I understand, but when I make some tests, I have some difficulties to check the Flight behavior.
Using 

``` php
Flight::view()->set('name', 'Bob');
```

anywhere in a class, doesn't give me an access to

``` php
Flight::view()->get('name', 'Bob');
```

in the next called view ran from a redirect

**Comment by mikecao** [comment]
If you redirect you're generating a **new** HTTP request. Whatever was in memory is now gone.

**Comment by gmoisio** [comment]
Ok, understood...
