### ISSUE TITLE
problem with css and javascript urls

### ISSUE THREAD

**Issue by weasr** [mikecao/flight#103]
Hello and thanks for this great framework.
I have a small problem that might be very easy to solve for you as I'm quite new to this:

I have this code :
Flight::route('/sidebar/@param', function( $param)
{

```
$session = Flight::get('session');
if ($session->isLoggedIn())
{
    ...
    Flight::render('header.php', array(), 'header_content');                                
    Flight::render('sidebar.php', array( 'user_info' => $info,
                                          'active'   => $param ), 'sidebar_content');
    ...
    Flight::render('layout.php', ....);
    ...
```

The parameter param is passed correctly to sidebar.php but when layout.php
 is rendered the keyword "sidebar" is added to all url for all css and javascript links in header.php and my page has no css nor javascripts loaded.
 Is this the way it should work ? If not how can I solve it? 

 advice appropriated.

many  thanks

**Comment by philo23** [comment]
Could be wrong, but it sounds like you're using relative URLs in your HTML, you'll probably want to use absolute URLs instead, for example: `/javascript/jquery.js` instead of `javascript/jquery.js`, or prefix them all with your domain `http://www.domain.com/javascript/jquery.js`

**Comment by weasr** [comment]
thanks allot , you are probably right , will try to use absolute URLs instead.
But I wonder why I only see this problem when I'm using route with parameters. My other routes without parameters are working just fine!.

**Comment by frankmaniaz** [comment]
Yo tuve el mismo problema lo he solucionado asignando a la variable de fligh la ruta absoluta del sitio:
Flight::set(''flight.base_url', '//localhost/rutaasuproyecto');

luego en la vista :

<?=Flight::get('flight.base_url')?>

Saludos

**Comment by myselfsufiyan** [comment]
@weasr you can use: 

`<script src="<?= Flight::get('flight.base_url') ?>views/js/jquery.min.js"></script>`

this just works fine for me...

**Comment by dantestopp** [comment]
@muhammadsufiyan 
If you set the baseurl to `//localhost/sub_directory` you will have some problems with the `Flight::redirect()`-Method.

For Example if you run the redirect `Flight::redirect('/user')` the Url from the redirect will result in `//localhost/localhost/sub_directory/user`.

The Problem can be solved if you don't use the `//localhost` in the baseurl and just define `/sub_directory` as baseurl.
