### ISSUE TITLE
Session in flight

### ISSUE THREAD

**Issue by frankmaniaz** [mikecao/flight#106]
As flight sessions start in php?

**Comment by mikecao** [comment]
Flight does not do anything with PHP sessions. You'll have to handle it yourself.

**Comment by Conver** [comment]
Is it planned to include session and/or cookies handling in Flight?

would be very great if so.

**Comment by jimlei** [comment]
Afaik Flight is so minimalistic it would advise to include some other session handler. There are quite a few available through packagist.

If you want a more complete framework out of the box there are multiple levels "up" from the bare bones of Flight. [Slim](http://www.slimframework.com/) is kind of a Flight+session+flash messages+logging, [Silex](http://silex.sensiolabs.org/) is similar (a micro-Symfony) and in the entire other end you have Laravel/Symfony that are quite huge Frameworks including "everything".

**Comment by Conver** [comment]
@jimlei I know about the other frameworks :) but I love Flight, and what all my apps are coded in.

Since cookies or sessions are something almost every app uses, it would be a good idea to include it in Flight, just me thoughts.

**Comment by jimlei** [comment]
@mikecao would you consider a PR for Flight::session()?

**Comment by mikecao** [comment]
@jimlei I'd have to think about the session support. When using native PHP session things can get really messy and you have to figure out how the user's environment is configured. Even Slim doesn't support native sessions. Writing to `$_SESSION` is easy enough, but you have to make sure `session_start` is called at the right time. Cookie support I think should be doable though.
