### ISSUE TITLE
Register Facebook Class

### ISSUE THREAD

**Issue by mcjj** [mikecao/flight#107]
Is this the right way to register facebook php sdk class?

Flight::register('facebook', 'Facebook',  array('appId'  => FACEBOOK_APPID, 'secret' => FACEBOOK_SECRET) );

Result:

Notice: Undefined offset: 0 in E:\xampp_php5416\htdocs...\flight\core\Loader.php on line 120

Notice: Undefined offset: 1 in E:\xampp_php5416\htdocs...\flight\core\Loader.php on line 120

I tried this codes too: 

Flight::register('facebook', 'Facebook',  array(FACEBOOK_APPID , FACEBOOK_SECRET ) );

result:

Warning: Illegal string offset 'appId' in  ...\facebook\base_facebook.php on line 251
Warning: Illegal string offset 'secret' in ...\facebook\base_facebook.php on line 252

I looked at the flight\core\Loader.php line 113 it seems it cannot handle parameters like this: 

 array('appId'  => FACEBOOK_APPID, 'secret' => FACEBOOK_SECRET) 

Or I'm missing something and doing it wrong?

Please advise anyone?
- many thanks

**Comment by mikecao** [comment]
According to the documentation this is proper way to initialize the Facebook class:

``` php
  $config = array(
      'appId' => 'YOUR_APP_ID',
      'secret' => 'YOUR_APP_SECRET',
      'fileUpload' => false, // optional
      'allowSignedRequest' => false, // optional, but should be set to false for non-canvas apps
  );

  $facebook = new Facebook($config);
```

So you need to do:

``` php
Flight::register('facebook', 'Facebook', array(array('appId' => FACEBOOK_APPID, 'secret' => FACEBOOK_SECRET)));
```

The register method takes an array of parameters to pass to the constructor. But the Facebook class expects a configuration array. So you need an array of an array.

**Comment by mcjj** [comment]
Thank you mike :+1:  by the way great framework :)
