### ISSUE TITLE
Explain why data is missing after Flight:json

### ISSUE THREAD

**Issue by romanov** [mikecao/flight#109]
Hello! Great framework, horewer i can't understand things below...

```
Flight::route('POST /test', function(){

    $request = Flight::request()->data;

    print_r($request);
});
```

I get and it's OK:

```
[data:flight\util\Collection:private] => Array
        (
            [varOne] => 2
            [varTwo] => 444
        )
```

But when i change my controller to return json:

```
Flight::route('POST /test', function(){

    $request = Flight::request()->data;

    Flight::json($request);
});
```

I get:

```
{}
```

Thank you for any help)

**Comment by mikecao** [comment]
`Flight::request()->data` is actually an object called a Collection, not an array. The original data is stored inside a private internal array so that's why you can an empty json string when it tries to encode the object. To get the actual data as an array, you'll want to do this:

``` php
$data = Flight::request()->data->getData();
```
