### ISSUE TITLE
Path and URL problem when using a example/example1

### ISSUE THREAD

**Issue by dco5** [mikecao/flight#112]
When I am using a route like this: 
Flight::route('/proyectos/proyectos1', function(){
    Flight::render('navegation',array(),'nav');
    Flight::render('proyectos1', array(), 'body');
    Flight::render('layout');
});
My css path and scripts is wrong. Example
http://localhost/example/proyectos/css/style.css
and it should be:
http://localhost/example/css/style.css

Also the links in the navegation are wrong:
http://localhost/example/proyectos/contact
and it should be:
http://localhost/example/contact

If I just use 
Flight::route('/proyectos', function(){.....}
Everything is good and all works.

Any ideas how to solve this? I am probably using this wrong.

**Comment by mikecao** [comment]
Flight doesn't do anything to links references in templates file. Make sure you are using the correct format for your links, either relative (css/style.css) or absolute (/css/style.css).

If you are running flight in a subdirectory, you don't need to specify it in your routes, like

Flight::route('/subdir/dir/', function() ...

You can just do:

Flight::route('/dir', function() ...
