### ISSUE TITLE
New instance of flight\Engine when using composer?

### ISSUE THREAD

**Issue by olssonm** [mikecao/flight#113]
I would like to run Flight as an object instance instead of globally. However, when I load Flight through Composer, I can see that the Flight composer.json-file autoloads flight\Flight.php instead of the Flight autoloader. 

Which means that I can't create an instance the "standard" way:

```
require(__DIR__ . '/vendor/autoload.php');

use flight\Engine;

$app = new Engine();
$app->route('/', function(){
    echo 'Hi there';
});
$app->start();
```

Instead Flight seems to want me to load the Flight autoloader directly (as shown in the [manual](http://flightphp.com/learn#methods)) – however, that makes Composer kind of useless in this scenario with multiple requires. 

Is there some more proper way to bypass this – or am I just missing something?

**Comment by mikecao** [comment]
I've updated the composer.json file so that it will load the Flight autoloader, so you should be able to use Flight from composer directly.

**Comment by olssonm** [comment]
Works like a charm, great!
