### ISSUE TITLE
Weird route match behaviour - named params with separating dashes

### ISSUE THREAD

**Issue by jimlei** [mikecao/flight#119]
Might just be me

URL:
mysite.com/blog/13-a-blog-post.html

Route:
Flight::route('GET /blog/@id-@title.html', ['PostController', 'getSingle']);

---

I would have thought this would result in:

$id = 13
$title = 'a-blog-post'

But instead it gives me this

$id = '13-a-blog'
$title = 'post'

---

Is this correct behaviour? If so, what would be the best way to split them like I want, when the title will have different lengths

**Comment by mikecao** [comment]
The named parameters only match whole URL segments. If you need it split up then you will have to do your own regex processing afterwards.

``` php
Flight::route('GET /blog/@page', function($page){
  // Analyze the $page parameter
});
```
