### ISSUE TITLE
Missing header variable causing error

### ISSUE THREAD

**Issue by songyanho** [mikecao/flight#122]
I managed to send an extra header variable from my AngularJS and if someone viewing the page without that particular header variable, it ends up with an error

```
<h1>500 Internal Server Error</h1><h3>Undefined index: XXXX_XXXX
```

I planned to use the Flight::has('id') to check the existence of the $_SERVER["XXXX_XXXX"] but I do not know how to use this command.

Please help.

**Comment by quanglam2807** [comment]
I have pulled a commit https://github.com/mikecao/flight/pull/120

You can use it:

```
Flight::request()->getVar('custom',default_value);
```

Ex:

```
$xx = Flight::request()->getVar('XXXX_XXXX','not_found');
if ($xx == 'not_found') {
     // XXXX_XXXX does not exist
}
```

Hope it help.
