### ISSUE TITLE
How can I use a common template for all route?

### ISSUE THREAD

**Issue by Zjmainstay** [mikecao/flight#123]
As far as I know, I can use the code bellow to show up my page. But how can I use a method to set a common template just auto call in all route method.

``` php
Flight::route('/', function(){
    Flight::view()->set('title', 'Home');
    Flight::render('templates/simple.php');
});

Flight::route('/login', function(){
    Flight::view()->set('title', 'Login');
    Flight::render('templates/simple.php');
});
```

**Comment by mikecao** [comment]
You can do something like this:

``` php
Flight::route('/@page', function($page){
  Flight::view()->set('title', $page);
  Flight::render('templates/'.$page.'.php');
});
```

**Comment by Zjmainstay** [comment]
This is not what I want. I want to trigger a method that just like

``` php
function loadTemplate() {
    Flight::render('templates/simple.php');  // simple is my current template
}
```

and it can auto call in each route method, because the template is a common one for each route method.

**Comment by mikecao** [comment]
You will have to manually call your function in each route. There is no way to attach a function to every route. The best thing you can do is to cover as many cases as possible (like using @page) so you don't have to repeat yourself so often.

**Comment by wilsonglasser** [comment]
How about using hooks/triggers, today Flight already use triggers, you could just implement some events like "Before route", "After route", something like that.
Ex.:
Flight::bind("before_route", function () {
    // global things
});

**Comment by mikecao** [comment]
Yes you could use the existing events `after start` or `before stop`.

``` php
Flight::before('stop', function(){
  Flight::render('templates/simple.php');
});
```

But a better solution would be to just map your own front controller and then pass all your routes through it. Otherwise you're going to be rendering a template for all requests, even JSON or POST, which may not be what you want.

**Comment by Zjmainstay** [comment]
OK, `before stop` solve my problem, thank you very much!
