### ISSUE TITLE
Error 404 - Document not found

### ISSUE THREAD

**Issue by ghost** [mikecao/flight#127]
[Wed Jul 16 22:43:25 2014] [error] [client xx.xx.xx.xx] File does not exist: C:/Program Files (x86)/Apache Software Foundation/Apache2.2/htdocs/a

``` php
<?php
require 'flight/Flight.php';

Flight::route('/', function(){
echo 'first / route matched';
});
Flight::route('/a', function(){
echo 'second a route matched';
});
Flight::start();
?>
```

The issue I'm having is when calling the first / route, it works, get the correct response. When calling the '/a' i get:

Not Found

The requested URL /a was not found on this server.

I feel like this is a noob thing, but I can't see where I'm going so wrong

**Comment by jimlei** [comment]
Have you added the rewrite rules to .htaccess as defined here: http://flightphp.com/install ?

**Comment by ghost** [comment]
Hi @jimlei. Yes. For a bit more context, I'm running Apache 2.2 on Windows Server 2012

This is the file location for the index.php and .htaccess:
C:\Program Files (x86)\Apache Software Foundation\Apache2.2\htdocs

And here's the content:
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]

edit: p.s. thanks for getting back so quickly

**Comment by jimlei** [comment]
Hm, seems like the url rewriting isn't working. To make sure you can start your index.php file with

``` php
die('this request was sent to the index.php file');
```

visiting any flight route should now show that message, if not that means the request isn't redirected to index.php. So if you still get the not found on /a you have to figure out why apache mod rewrite isn't working.

Common errors:
- rewrite module not loaded
- wrong filename on the .htaccess file, might have a .txt extension or similar as windows won't let you create files without a name
- apache / vhost config set up to now allow .htaccess files to override them.

You can add the rewrite rules directly to the vhost config to see if that makes any difference.

**Comment by ghost** [comment]
Bang on. mod_rewrite was commented out.

takk, takk!

**Comment by Tolsi** [comment]
It turns out you can not use this engine with built-in php server? it is convenient for development.

**Comment by mikecao** [comment]
@Tolsi You can't use this framework or any other framework that requires rewriting URLs. If the PHP server can't do that then it's not possible.

**Comment by vanilla-thunder** [comment]
sorry for reviving this old thread, but this is one of top 5 search results on google and in case someone having same problem on apache 2.4 despite .htaccess and **AllowOverride All** in vhost config:
My solution was removing *_Options +Indexes +... *_ from vhost config.

Hopefully it helps somebidy.
cheers

**Comment by benjaminpeljto** [comment]
![image](https://user-images.githubusercontent.com/80229691/227960759-34c620fd-4f4c-4fab-a712-40535c4a9b4f.png)
This doesn't work, but this:
![image](https://user-images.githubusercontent.com/80229691/227961036-19daeffc-0558-496d-ba65-2df36692c582.png)
works! Why is that and can I do something about it because it is going to make problems in further development?
