### ISSUE TITLE
Wildcards: get given params?

### ISSUE THREAD

**Issue by CodeBrauer** [mikecao/flight#128]
Hi,

``` php
Flight::route('/categories/*', function(){
    // Request URI: /categories/pictures/2013/10/10/drafts
});
```

That's similiar to the documentation example. But how can I get the params?
Like this e.g.

``` php
['pictures','2013','10','10','drafts']
```

every function param produces an error... I need this as wildcard cause the depth of params is dynamic (filepath)

Hope you can help me.

BTW: Best "minimalistic" micro framework so far.

**Comment by jimlei** [comment]
Flight uses @param to map url pieces to variables, since you don't have any you won't get any params. I think your best bet would be to explode the request url on / and assign params yourself (or just use the resulting array)

``` php
Flight::route('/categories/*', function(){
    $params = explode('/', Flight::request()->url);
    print_r($params);
});
```

```
Array ( [0] => [1] => categories [2] => pictures [3] => 2013 [4] => 10 [5] => 10 [6] => drafts ) 
```

Or if you have a static url scheme you could do this

``` php
Flight::route(
    '/categories(/@category(/@year:[0-9]{4}(/@month:[0-9]{2}(/@day:[0-9]{2}(/@type)))))',
    function($category, $year, $month, $day, $type){
});
```

In this example all the params in the route are optional (but have static placement)

If you want to move "drafts" out to the end of any matching url you could do this

``` php
Flight::route(
    '/categories(/@category(/@year:[0-9]{4}(/@month:[0-9]{2}(/@day:[0-9]{2}))))(/@type)',
    function($category, $year, $month, $day, $type){
});
```

Now you can add /drafts  behind any of the urls matching the route.

```
/categories/drafts
/categories/pictures/drafts
/categories/pictures/2014/drafts
etc
```

**Comment by CodeBrauer** [comment]
ok thank you. thats maybe not the way i think to do it but still better than working with `$_SERVER['REQUEST_URI']`

**Comment by jimlei** [comment]
You could implement it so that wildcard routes return all url parts as params or an array, and issue a pull request. If the framework devs think it's a good idea they might include it :)

**Comment by wilsonglasser** [comment]
Why not just return the params if only wildcard without any maps is used,
this reduces people work and is a valid solution for a framework.

/categories/\* should return everything after /categories/ breaking by "/".

Atenciosamente,
Wilson Glasser

2014-07-17 9:19 GMT-03:00 Jim Leirvik notifications@github.com:

**Comment by CodeBrauer** [comment]
Maybe i will try to code a PR for that. Now I haven't that much free time :sleeping:
