### ISSUE TITLE
Routing settings /user/*  Cannot jump notFound(404.html)

### ISSUE THREAD

**Issue by fangjunai** [mikecao/flight#131]
//路由里设定/user/\* 无法跳转到 notFound  
// Routing settings /user/\*  Cannot jump notFound(404.html)
//url : If /user/xxxx 

//用户中心 - 验证
//user- checking
Flight::route('/user/*',function(){
    if(!isset($_SESSION['USER']) || empty($_SESSION['USER'])){
        Flight::redirect('/user/login');
        return false;
    }
    return true;
}

//最后 未找打匹配路由 则显示自定义错误页面404
Flight::map('notFound', function(){
        include './views/errors/404.html';
})

**Comment by jimlei** [comment]
Your code is invalid. The route is missing the ending ); while the map is missing the ending ;

I suggest you use an editor with markup/error highlighting. A free IDE like Netbeans will show you these kinds of errors :) As a bonus IDEs have a simple way of formatting the code so you get everything indented correctly. Indention might have dissappeared after pasting here as well though.

bonus: empty checks if the variable is set and if it's empty. so you don't need to do both :)

``` php
//路由里设定/user/* 无法跳转到 notFound
// Routing settings /user/* Cannot jump notFound(404.html)
//url : If /user/xxxx
//用户中心 - 验证
//user- checking
Flight::route('/user/*', function() {
  if (empty($_SESSION['USER'])) {
    Flight::redirect('/user/login');
    return false;
  }
  return true;
});

//最后 未找打匹配路由 则显示自定义错误页面404
Flight::map('notFound', function() {
  include './views/errors/404.html';
});
```

**Comment by fangjunai** [comment]
Thank you!  
I use to eclipse for php, How to judge the user login?

**Comment by jimlei** [comment]
> How to judge the user login?

Not clear what you're asking, please consider rephrasing the question
