### ISSUE TITLE
Route Does Not Allow Periods or Dots

### ISSUE THREAD

**Issue by Skinner927** [mikecao/flight#132]
Using latest commit: c0fa0bed7c893694c640224db22a221d8bbdff4e

With a route like this: 
`Flight::route('GET /data/@table/@query', function($table, $query){
...
});`

A url of: `/data/foo/bar` will work
but a url of: `/data/foo/bar.barf` will not be caught by this route.

How do I allow periods to be included in my route? Even a splat will not work.

**Comment by wilsonglasser** [comment]
With the last version this already work.

Atenciosamente,
Wilson Glasser

2014-07-31 0:12 GMT-03:00 Skinner927 notifications@github.com:

**Comment by mikecao** [comment]
I can't reproduce this issue. URLs with dots works for me.

**Comment by mondolirondo** [comment]
I had the same issue.
Just in case somebody else arrives here hoping to find a solution or at least an explanation, **it seems to be a bug of PHP's built-in web server**:
https://stackoverflow.com/a/32098723
https://bugs.php.net/bug.php?id=61286
Nothing to do with Flight itself.
I was developping my application in Netbeans using PHP's web server and had to switch to a local Apache server to avoid the problem.

**Comment by geek-at** [comment]
To solve the problem you need to add this to your router script

```php
if (PHP_SAPI === 'cli-server') {
  $_SERVER['SCRIPT_NAME'] = pathinfo(__FILE__, PATHINFO_BASENAME);
}
```

source: https://stackoverflow.com/a/51756815/1174516
