### ISSUE TITLE
More releases to packagist

### ISSUE THREAD

**Issue by chrisivens** [mikecao/flight#133]
Any chance we can have more tagged versions pushed to packagist. This should help with version locking when needed in composer.json

**Comment by mikecao** [comment]
I've just tagged a couple more versions. Current release is now officially v1.2.

**Comment by chrisivens** [comment]
Thanks. I inherited an app that works on 1.1.8 and is broken on 1.1.12 so it'd be great to use proper versions in future rather than commit hashes.

Much appreciated.
