### ISSUE TITLE
Facebook SDK

### ISSUE THREAD

**Issue by frederichoule** [mikecao/flight#137]
Any way to properly load the new Facebook PHP SDK?

**Comment by mikecao** [comment]
Not sure what you mean. If it's simply a class, then just use the `Flight::register()` method.

**Comment by frederichoule** [comment]
No there's like 50 classes that uses autoload.php.

I've been able to make it work by requiring about 20 php files from the src
directory, can't get the autoload to work.

Sent with my SGN2

**Comment by mikecao** [comment]
The Facebook autoload.php should be loading all those classes for you. You can try using the `Flight::path()` method and have Flight try to autoload the classes, but I would recommend just getting the Facebook autoloader to work.

**Comment by faridelnasire** [comment]
@frederichoule did you end up getting this to work?

**Comment by frederichoule** [comment]
I had to include each and every Facebook class files one by one to make it
work.

**Comment by JustSteveKing** [comment]
I always use : `"require" : { "lusitanian/oauth": "0.3.*" }` for OAuth SDK stuff. That way I can build my own class to talk to the OAuth service and do not need to load as much in.
