### ISSUE TITLE
Use $route in Flight::before ?

### ISSUE THREAD

**Issue by CodeBrauer** [mikecao/flight#139]
How can I get the "$route"-data in the before start function?

``` php

Flight::before('start', function($route, &$output){
    var_dump($route->methods);
});
```

`$route` is an empty array
`$route->methods` isn't set.

**Comment by mikecao** [comment]
You can't because the route object will only be passed to a matching route's callback. Before start, the router hasn't even initialized yet.

**Comment by CodeBrauer** [comment]
Okay. I wanted to log any route that is going to be called. I will use just use `$_SERVER` and built in PHP functions for that.

Thanks for the fast response.
