### ISSUE TITLE
Incorrect HTTP status returned

### ISSUE THREAD

**Issue by vitriol** [mikecao/flight#14]
<?php
require 'flight/Flight.php';

Flight::route('/', function(){

   Flight::json(array());
});

Flight::start();
?>

Json string is correctly returned, but the response status is 500. 
Server does not log any errors.

**Comment by mikecao** [comment]
I can't seem to replicate it. How are you testing for the return status? I'm using the HttpFox extension in Firefox and it correctly returns 200.

**Comment by vitriol** [comment]
Hmm... Firebug and also cmdline curl. I tested on different machines/ OSs and the same. I made no other changes to anything, I don't get this.

**Comment by mikecao** [comment]
Did you try different web servers as well as clients? If you're connection through different clients and getting the same error it could be a server configuration issue.

**Comment by qlimax86** [comment]
I confirm the same issue.
Http server: Apache2 + mod_php
Server Os: Ubuntu Linux 10.04
Client: GoogleChrome / jQuery.get()

Workaround:
header("Content-type: application/json");
echo json_encode(array());

**Comment by mikecao** [comment]
I had to install Apache to figure it out. There was an error in the way it was setting the status code. Now fixed in commit 5f98e1e06c04f484d7647358a56712b1817c453c.

**Comment by qlimax86** [comment]
Thanks for the fix. I also wanted to thank you for the great work you did with this project!
