### ISSUE TITLE
problem with mail sending

### ISSUE THREAD

**Issue by venu8** [mikecao/flight#140]
how  send email by using flight framework

**Comment by jimlei** [comment]
Flight is a micro framework that only include the bare minimum to get a project running. For tasks like mail you should add a mail package and use that.

Ie
https://github.com/PHPMailer/PHPMailer/blob/master/README.md

Include it in composer.json, run composer install and composers autoloader should now load both flight and phpmailer.

Then you can just register it to Flight so you can use it all over your code.

**Comment by venu8** [comment]
thanks for useful information
