### ISSUE TITLE
Splat is not correct when a named param is present in a route pattern

### ISSUE THREAD

**Issue by kouts** [mikecao/flight#142]
Image a route like this
Flight::route('/@namedparam/*', function($blog, $route){
    var_dump($route);
}, true);

a URL like this http:://www.mydomain.com/mynamedparam/1/2/3/4/5/6
will return a splat like this: /2/3/4/5/6 which is wrong.
The correct splat should be: 1/2/3/4/5/6

Here is the fix:

Replace: line 85 in Route.php ($this->splat = substr($url, strpos($this->pattern, '*'));)
with this code:

$asterisk = explode("*", $this->pattern, 2);
$no_of_slashes = substr_count($asterisk[0], '/');
$url_pieces = explode("/", $url);
$url_pieces = array_slice($url_pieces, $no_of_slashes);
$this->splat = implode("/", $url_pieces);

**Comment by mikecao** [comment]
Thanks, fixed in commit 88f4c1fb7108d11240e2db341be641f388d52124.
