### ISSUE TITLE
function to get all $vars

### ISSUE THREAD

**Issue by kouts** [mikecao/flight#147]
Can we have a function to get all $vars like getAll() or something? Also it would be great if we could set array keys in $vars. In php 5.4 I can get `app::get('my_array')['key']` but how can I set `$vars['my_array']['key']?`

**Comment by kouts** [comment]
Maybe implement the $vars array as a flight\util\Collection?

**Comment by mikecao** [comment]
Now in commit ef76d72b56eccccfd8d029c0b1aa53388d3ed3b2. Just do `$vars = Flight::get();`.

**Comment by kouts** [comment]
Worked great, thanks.
