### ISSUE TITLE
Routing doesn't show 404 after return true;

### ISSUE THREAD

**Issue by RvZ** [mikecao/flight#157]
Routing works fine but i have one problem.

I don't get the 404 error but a empty page if my url match with a route and i use `return true;` to abort the route. if there is no match it shows the 404 error like it should.

I use a workaround now i don't return true but just run `Flight::notFound();`

Flight::route('/@@username/', function($username) //return true works;
Flight::route('/@slug/', function($slug) //return true = show black page;

I'm working on a windows server using Ionics Isapi Rewrite Filter
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^/.*$ /index.php [L,QSA]

**Comment by jonathanhecl** [comment]
I use a variable for the "path"...

---

require 'flight/Flight.php';
$path= '/test/flight';

Flight::route($path . '/hello', function(){
...........

---

Work in the navigator url like http://localhost/test/flight/hello

Regards!

**Comment by mikecao** [comment]
This is now fixed in commit 7c50eb7cfb13e288dec2b1cd0db434e402752564. If you return `true` and no other routes match, it should return a 404.
