### ISSUE TITLE
How get a variable in class from route

### ISSUE THREAD

**Issue by jonathanhecl** [mikecao/flight#158]
How get any variable in a class file...

I read for routes normal is:

---

$name= "Pepe";
Flight::route('/', function() use ($name) {
    echo "Hello " . $name;
});

---

But for class, i only find this...

---

Flight::set('name', 'Pepe');
Flight::route('/', array('start', 'hello'));

---

And Flight::get('name') to show...

Exists another form to get the variable in class without use "set" or "get"??

**Comment by qlimax86** [comment]
You can use globals.
http://php.net/manual/it/reserved.variables.globals.php

Or for settings like things, you can define constants 
http://php.net/manual/it/function.define.php

or define non static methods and use params

``` php
Flight::route('/', function() use ($name) {
   $s = new start();
   $s->hello($name)
});
```

**Comment by jonathanhecl** [comment]
Thanks

What is the most optimal method? global, define, params or set/get of Flight?

**Comment by qlimax86** [comment]
If the value doesn't have to change (e.g a path or the domain name), use define. Else use a param.
