### ISSUE TITLE
redirect when param not set

### ISSUE THREAD

**Issue by ang3lx** [mikecao/flight#159]
hello,

what can I do to force redirect when param not set.
I will explain with an example

user open link www.domian.tld/about-us

but matching pattern is
Flight::route('/@lang:[a-z]{2}/@title/', array('PageController','page'));

correct link should be www.domian.tld/en/about-us

so i should force link with redirect www.domian.tld/about-us -> www.domian.tld/en/about-us
how can I do this?

thanks in advance

**Comment by mikecao** [comment]
You can do something like this:

``` php
$allowed = array('en', 'de', 'fr');

Flight::route('/@lang/@title', function($lang, $title) use ($allowed) {
  if (!in_array($lang, $allowed)) {
    Flight::redirect('/en/'.$title);
  }
});
```

**Comment by ang3lx** [comment]
this solution is valid if someone use not allowed language
but if you use www.site.com/title without /lang/ return 404

i would redirect from domian.tld/about-us (301) to domian.tld/en/about-us

**Comment by mikecao** [comment]
Then do `/@lang(/@title)` so that title is now optional.
