### ISSUE TITLE
Flight::json + Flight::lastModified conflict

### ISSUE THREAD

**Issue by philo23** [mikecao/flight#16]
If you use `Flight::json` and `Flight::lastModified` at the same time, the `Last-Modified` header is never sent, which means the `If-Modified-Since` header can never be correctly handled.

It seems to be down to `Flight::json` behind the scenes using a new instance of the `flight\Response` class in `flight/Flight.php` around line 400.

This can easily be quite easily reproduced with the following routes:

``` php
Flight::route('flight_json', function () {
    // Broken example using Flight::lastModified + Flight::json
    $modified = strtotime("2012-11-12 00:00:00");
    Flight::lastModified($modified);

    $json = array(
        'uts_modified' => $modified,
        'type' => 'Flight::json'
    );
    Flight::json($json);
});

Flight::route('json_encode', function () {
    // Working example using Flight::lastModified and manually echoing json_encode
    $modified = strtotime("2012-11-12 00:00:00");
    Flight::lastModified($modified);

    $json = array(
        'uts_modified' => $modified,
        'type' => 'Flight::json'
    );

    // Same as Flight::json method but doesn't use a new instance of the response object
    Flight::response()
        ->status(200)
        ->header('Content-Type', 'application/json')
        ->write(json_encode($json))
        ->send();
});
```

Is this the expected behaviour with a reason why a new instance of `flight\Response` is used or simply an oversight?

**Comment by mikecao** [comment]
It was an oversight. Thanks for reporting it.

Now fixed in commit 9a115b84abef3cbe71d74a31ebc9914ea8694e04.
