### ISSUE TITLE
When using wild card to parse a sub route the routing is not resulting in the correct path

### ISSUE THREAD

**Issue by andrevanzuydam** [mikecao/flight#161]
Route /test/\* will not match <weburl>/test/test/test/test

Temporary Solution - the base route needs to be passed with to matchUrl in route call if the base route is not a ".".

**Comment by n0nag0n** [comment]
This is actually fixed now. https://github.com/flightphp/core/commit/0b149349fcead1909ea8d03c85670ef9d089203a
