### ISSUE TITLE
Hooks for filtering request()->query and request()->data

### ISSUE THREAD

**Issue by warmwaffles** [mikecao/flight#17]
Often I am finding myself having to encapsulate the request()->query in a cleaning function of my own. I would love to have the ability to attach filters to it so I don't have to keep doing something like this:

``` php
$clean = Security::clean(Flight::request()->data['someval']);
```

**Comment by mikecao** [comment]
You can create a filter before the start event like this:

```
Flight::before('start', function(){
    $query =& Flight::request()->query;
    foreach ($query as $k => $v) {
        $query[$k] = Security::clean($v);
    }
});
```

**Comment by warmwaffles** [comment]
Yea the same would have to go for the `data` field as well.

EDIT:
To be honest, I would much rather lazy load the clean than to run it on every value at every run.

**Comment by mikecao** [comment]
You can map your own function to do that:

```
Flight::map('getClean', function($var){
    return Security::clean(Flight::request()->data[$var]);
}

$clean = Flight::getClean('someval');
```

**Comment by warmwaffles** [comment]
I like that solution a lot more.
