### ISSUE TITLE
Regex doesn't work in optional routing parameters

### ISSUE THREAD

**Issue by jammesz** [mikecao/flight#23]
I've noticed that you can't put any regex filters in an optional parameter for routes.
E.g.

``` php
Flight::route('/@controller/@method(/@id:[0-9]+)', function($controller, $method, $id){
    ...
});
```

**Comment by mikecao** [comment]
What error message are you getting? I ran a test and it seems to be working for me.

**Comment by lucasrubini** [comment]
I had noticed that too, and for the example above I get a 404 error if @id is empty.

**Comment by jammesz** [comment]
I get the same error as lucasrubini if @id is empty. I just did another test with /@controller/@method(/@id) and that doesn't work either, giving the same 404 error. I am not using the latest Flight though, I have searched everywhere for a version number but couldn't find one. Before posting I checked the commits, issues, and merges for anything that might have addressed this issue but couldn't find one. I will download the latest and test it.

**Comment by jammesz** [comment]
Ok so after downloading the latest version from your website the route /@controller/@method(/@id) does work. However, /@controller/@method(/@id:[0-9]+) still produces a 404 error when @id is empty

**Comment by mikecao** [comment]
@jammesz I really do need to do a better job at adding version numbers. I'll work on that.

In the meantime I can confirm this is an error and will work on a fix.

**Comment by jammesz** [comment]
Even just a variable holding the version number would be good enough or just in the comment area up the top of the main flight.php. I think the old version I had was from 2011 (judging from the copyright comment).

**Comment by lucasrubini** [comment]
I've worked on a match method that works with these kinds of patterns (e.g., /@controller/@method(/@id:[0-9]+)). I can post it if you'd like.

**Comment by lucasrubini** [comment]
Well, here it goes:

```
public function match($pattern, $url) {
    $this->paramNames = array();

    // Build the regex for matching
    $regex = preg_replace_callback(
        '#@([\w]+)(:([^/()]*))?#',
        function($matches) {
            $this->paramNames[] = $matches[1];
            if (isset($matches[3])) {
                return '(?P<' . $matches[1] . '>' . $matches[3] . ')';
            }
            return '(?P<' . $matches[1] . '>[^/]+)';
        },
        str_replace(')', ')?', $pattern)
    );
    if (substr($pattern, -1) === '/') {
        $regex .= '?';
    }
    if (substr($pattern, -1) === '*') {
        $regex = str_replace('*', '.+?', $pattern);
    }

    // Attempt to match route and named parameters
    if (preg_match('#^' . $regex . '$#i', $url, $paramValues)) {
        foreach ($this->paramNames as $name) {
            if (isset($paramValues[$name])) {
                $this->params[$name] = urldecode($paramValues[$name]);
            }
        }
        return true;
    } else {
        return false;
    }
}
```

**Comment by mikecao** [comment]
Now fixed in commit 61ce37ca641c475ef205d56e46eaf7943453dacb.

**Comment by jammesz** [comment]
Thanks but this returns 404 error for all pages now (except index). I would take a go but I'm not really that good at regex.

I think the syntax for optional parameters needs to be changed and the matching to be broken down. If it was changed to /(@id:[0-9]+) instead of (/@id:[0-9]+) you could explode both pattern and url to count how many segments are in the url and pattern to compare.

After exploding the pattern you would loop through to get the index of optional params. From this we could determine whether or not the url has the minimum number of segments to be passed onto to the matching part. If it has equal or more segments as the pattern with the optional param, then we can match against the option param as well.

Also if an optional param with regex doesn't match then all segments after that do not get matched even if they aren't optional i.e. break the loop and return false. I think this is how Flight's routing works anyway but wanted to make sure that a pattern like /@p1/@p2/(@op1)/test doesn't match /@p1/@p2/test which, in my opinion, is unwanted behavior (/@p1/@p2/test should return false if matched against /@p1/@p2/(@op1)/test).

What do you guys think?

**Comment by jammesz** [comment]
Thanks mikecao, I didn't reload the page and didn't see your commit when I posted above. Anyway the post above is just an idea.
