### ISSUE TITLE
Get rid of globals to allow for composing routes

### ISSUE THREAD

**Issue by rosejn** [mikecao/flight#24]
Flight is really clean and nicely written, but it would be great if we could compose routes, rather than having them all defined at just the top level.  For example, it could work like this:

image_api = Flight::api()

// route requests like: /images/birds/234
image_api::route('@category/@id')  

api = Flight::api()
api::route('/images/*', image_api)

Flight::run(api)

In this way an application could be decomposed into a set of APIs, each one of which can be defined in its own way, with its own filters, etc...

**Comment by rosejn** [comment]
Hmmm, I see now that since Flight isn't persistent, it would be reasonable to just put different sub-apis into different directories or files...  maybe this isn't necessary.

**Comment by mikecao** [comment]
Not sure what you mean by persistent, but you can simply route different directories to their own handlers:

```
Flight::route('/images/*', function(){
  // Image API functionality
});

Flight::route('/users/*', function(){
  // User API functionality
});
```
