### ISSUE TITLE
How do you call something on start and end of framework?

### ISSUE THREAD

**Issue by dubcanada** [mikecao/flight#28]
Hello,

I am trying to figure out how Flight::after and Flight::before work. I am calling something that outputs a timestamp in microseconds and I am trying to do it on start of the framework and after the "results" of the framework have been outputted.

However it seems to be getting called instantly, rather then on start/end of framework.

```
Flight::after('start', Profiler_Console::logSpeed('Start Application'));
Flight::after('render', Profiler_Console::logSpeed('End Application'));
```

output

```
0.04
0.17
```

I believe the start is correct but how can I call "stop" after everything is done (regardless of what kind of data was outputted)?

**Comment by mikecao** [comment]
First of all, you need to pass in a closure or callable function as the second parameter. So unless your `Profiler_Console::logSpeed` method returns a callable, it will just execute immediately. You will need to wrap it like this:

``` php
Flight::after('start', function(){
    Profiler_Console::logSpeed('Start Application'));
});
```

Then you would probably want to do `Flight::before('start', ...)` and `Flight::before('stop', ...)`. Start is the very first method called and Stop is the very last one.

**Comment by kamov** [comment]
How to show result ?

``` php
Flight::before('start', function(){
    Flight::set('starttime', microtime(true)); 
});

Flight::after('stop', function(){
    $time_end = microtime(true);
    $execution_time = ($time_end - Flight::get('starttime'))/60;

    // how to print result ??
    // echo $execution_time; // don't work
});
```
