### ISSUE TITLE
[Question] Changing the Flight "base" path.

### ISSUE THREAD

**Issue by thybag** [mikecao/flight#31]
Hello,

I was wondering whether there is a proper / more sensible way to go about altering a Flight Requests base path (without hacking the core).

The issue has come about in a system I'm working on where we are referencing the flight index.php from an .htaccess file in a different folder. As a result flight is getting passed paths with a "base" different from the `dirname($_SERVER['SCRIPT_NAME'])` it expects, which ends up throwing all the routing off.

To get around the problem I've end up essentially doing this (prior to the Flight::start(); ) which seems to work, although doesn't feel like a particularly clean solution.

```
      Flight::request()->base = '/app/public';
      Flight::request()->url = substr(Flight::request()->url, strlen(Flight::request()->base));
```

Just wondering if there is a "correct" way to set these options that I'm for some reason not seeing.

Thanks,
Carl

**Comment by mikecao** [comment]
Can you tell me a little more about your setup? How are you folders arranged and what is in your .htaccess file?

**Comment by thybag** [comment]
Hello,

The .htaccess file itself is pretty much the default, the only change being that its rewriting the URL to be a folder up from its normal location.

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ public/index.php [QSA,L]
```

The issue then comes about as the `$_SERVER['REQUEST_URI']` is unaware of the extra folders existence, meaning it sees the path as "/website/my/file/path" rather than the "/website/public/my/file/path". `$_SERVER['SCRIPT_NAMEI']` on the other hand still pulls back the "real" path which includes the public folder. 

The end result is that since the basename found isn't part of the url Flight is seeing, flight ends up trying to route on "/website/my/file/path" rather than "/my/file/path" which results in it 404ing.

I guessed that the best way to get around the issue would be to manually set the basename, although since the Request object appears to be created when flight starts, it turned out i also had to update the Request url parameter to reflect the basename change (as in the code in my first post).

My work around appears to work correctly so far, although still feels a little hacky. I wanted to double check there wasn't a proper way to achieve the same kind of result which i may have missed etc.

Thanks,.
thybag

**Comment by mikecao** [comment]
I think you're handling it correctly given the situation. I'll see if I can find a solution for setting the basename through the framework, possibly as a config.

You may also want to look into the RewriteBase directive and see if that helps.
