### ISSUE TITLE
Routing and objects

### ISSUE THREAD

**Issue by qlimax86** [mikecao/flight#32]
Hello,
I would like to propose a question:

At this time, this is what I'm doing to avoid the use of static methods:

``` PHP

$errorController=new ErrorController();
Flight::route('/error/pagenotfound',array($errorController,'pagenotfound'));
Flight::route('/error/browser',array($errorController,'browser'));

$homeController=new HomeController();
Flight::route('/',array($homeController,'index'));

```

However, when there are no errors, the $errorController object is created anyway.Thus I'm uselessly occuping memory.

Is there a smarter way of doing it? Some kind of lazy loading ?

Regards
Thank you!

**Comment by philo23** [comment]
You should just be able to write the classes name as a string just like any other "callable" type (see the second "call_user_func" example here: http://php.net/manual/en/language.types.callable.php), for example:

``` php
Flight::route('/error/pagenotfound',array('ErrorController','pagenotfound'));
Flight::route('/error/browser',array('ErrorController','browser'));

Flight::route('/',array('HomeController','index'));
```

**Comment by qlimax86** [comment]
Hi philo23,
thank you for the answer.

In that way, my controllers' methods are called in a static way (see Dispatcher::invokeMethod function ) , and is what I want to avoid.

**Comment by mikecao** [comment]
You can pass in a callback which instantiates your class only when it's called:

``` php
Flight::route('/error/pagenotfound', function(){
    $errorController = new ErrorController();
    $errorController->pagenotfound();
});
```

**Comment by qlimax86** [comment]
Hi mikecao,
thank you for suggesting me this solution.

However, if I have - let's say - 25 different error pages, I would have to repeat that 25 times.
I've tried with a routes array and loop over it, but then I faced some problems with parametrized routes.

It would be nice to have something like that:

``` PHP
Flight::route('/error/pagenotfound',array('ErrorController','pagenotfound',true)); 
```

Where **true** means createInstance.

What do you think about ?

**Comment by mikecao** [comment]
You would still be repeating yourself for every error page you have. Instead you can just use a url parameter:

``` php
Flight::route('/error/@name', function($name){
    $errorController = new ErrorController();
    $errorController->$name();
});
```

**Comment by qlimax86** [comment]
Yes, that's what I was looking for.
I didn't even think about this option...

Thank you very much for showing me the way!

Regards.
