### ISSUE TITLE
Flight, PHP and MySQL

### ISSUE THREAD

**Issue by zQueal** [mikecao/flight#34]
Unfortunately the documentation for Flight is rather lacking, and I'm unable to figure out how to properly query a MySQL database using Flight.

``` php
<?php

# Includes #
require_once('flight/Flight.php');

# Database Information #
Flight::register('db', 'Database', array('localhost', 'database', 'username', 'password'));

# Queries #
Flight::route('/name/@name:[a-zA-Z]', function($name) {
        $db = Flight::db();
        $db->connect();
        return($db->query("SELECT * FROM active WHERE short_name LIKE '$name' LIMIT 0, 30"));
});

Flight::route('/address/@address:[a-zA-Z0-9]', function($address) {
        # mysql query using $address
});

?>
```

A preview of the database:
![database](http://i.imgur.com/lukViEe.png)

And this is what the script returns:
![return](http://i.imgur.com/Kduqe8a.png)

Anyone able to led some help?

**Comment by warmwaffles** [comment]
Did you call `Flight::start()` at the end of the php file?

**Comment by zQueal** [comment]
@warmwaffles 

Honestly, I did not, and it makes me feel stupid. haha.

Revised:

``` php
<?php

# Includes #

require_once('flight/Flight.php');
/* require_once('config.php'); */

# Database Information #

Flight::register('db', 'Database', array('localhost', 'database', 'username', 'password'));

Flight::route('/name/@name:[a-zA-Z]', function($name) {
        $db = Flight::db();
        $db->connect();
        return($db->query("SELECT * FROM active WHERE short_name LIKE '$name' LIMIT 0, 30"));
});

Flight::route('/address/@address:[a-zA-Z0-9]', function($address) {
        # mysql query using $address
});

Flight::start();
?>
```

As of now, with this script when I query a name via `http://localhost/name/test` it returns `Error 500`. Any other suggestions?

**Comment by warmwaffles** [comment]
You need to check the error logs to see what is causing the 500.

**Comment by zQueal** [comment]
```
[Sat Apr 13 10:52:01 2013] [error] PHP Fatal error:  Class 'Database' not found in /var/www/html/flight/core/Loader.php on line 124
```

Database is a built in function to Flight, is it not?

**Comment by warmwaffles** [comment]
Negative. You have to use `PDO` or some other database.

``` php
<?php
Flight::register('db', 'PDO', array('sqlite:db/database.sqlite'), function($db) {
  $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
});
```

`Database` was just an abstract example.

**Comment by zQueal** [comment]
@warmwaffles,

I truly appreciate the assistance. That wasn't noted at all in the documentation, and I have zero experience with PDO. Some Googling and I was able to work around my inexperience and finally got it to work. :+1: 

``` php
<?php

# Includes #
require_once('flight/Flight.php');

# Database Information #

Flight::register('db', 'PDO', array('mysql:host=localhost;port=3306;dbname=database', 'username', 'password'), function($db) {
        $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
});


# Ruotes #
Flight::route('/name/@name', function($name) {
        $conn = Flight::db();
        $data = $conn->query("SELECT * FROM active WHERE short_name LIKE '$name' LIMIT 0, 30");

        foreach($data as $row) {
                print_r(json_encode($row));
        }
});

Flight::route('/address/@address', function($address) {
        # mysql query using $address
});

Flight::route('/', function() {
        echo 'Use correct syntax please.';
});

# Execute #
Flight::start();

?>
```

As you can see below the information returns just fine!

![return](http://i.imgur.com/jGxX6Nw.png)

As to why it's being returned twice, I have no idea! But I truly appreciate the assistance!

**Comment by warmwaffles** [comment]
There's an option to turn of the numerical values. Those are just the order in which they were returned from the database. Just need to look in the documentation for it.

**Comment by 848five** [comment]
@warmwaffles the numberical values, is that an option in flight that I can control?  I didn't see anything in the documentation.  can you point me in the right direction?

**Comment by warmwaffles** [comment]
@848five http://php.net/manual/en/book.pdo.php

**Comment by DanielGBullido** [comment]
$db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_OBJ);
