### ISSUE TITLE
Go to next route

### ISSUE THREAD

**Issue by searchinnerpeace** [mikecao/flight#35]
Is there a way to go to the next route, like this:

Flight::route('GET /admin/*', function(){
  //Apply authentication
  Flight::next();
});

Flight::route('GET /admin/posts', function(){
  //Business logic
});

Thanks.

**Comment by mikecao** [comment]
It is currently not supported but it's a good idea, so I will add it to the next release.

**Comment by searchinnerpeace** [comment]
Thanks

**Comment by mikecao** [comment]
Now available in commit 28ae5e0aecf13fbbaa593d0b11a12068b4062d02
