### ISSUE TITLE
Handling PUT or DELETE request

### ISSUE THREAD

**Issue by tareq1988** [mikecao/flight#36]
I didn't see any PUT or DELETE request handling in the docs. Is it yet supported? Thats the only thing is blocking me from using the framework for my backbone.js project.

**Comment by warmwaffles** [comment]
I don't see why it wouldn't. Have you tested it? (sorry if this sounds stupid)

**Comment by tareq1988** [comment]
No I haven't actually. Thats why I mentioned about the docs.

**Comment by warmwaffles** [comment]
Give it a shot, and if it does work. I can add an example to the documentation or @mikecao can.

**Comment by mikecao** [comment]
Yes, it is supported, as long as it's being passed to the web server properly. All it does is match the request method you enter to `$_SERVER["REQUEST_METHOD"]`. But be aware that html forms don't support PUT and DELETE methods.

**Comment by tareq1988** [comment]
Thanks, will give it a try. Was using Silex for now, but I am not feeling comfortable with it.

**Comment by kafene** [comment]
If you want to allow method overrides without depending on the server config or modifying flight directly, you can do this:

``` php
require 'flight/Flight.php';

$_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE'] = 'PUT';

Flight::before('start', function() {
    Flight::request()->url = getenv('PATH_INFO') ?: '/';
    if(isset($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE'])) {
        Flight::request()->method = $_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE'];
    } elseif(isset($_POST['_method'])) {
        Flight::request()->method = $_POST['_method'];
    }
});

Flight::route('PUT /', function(){
    echo 'Putting something?';
});
```

edit: nevermind the PATH_INFO part, I use that because I don't rewrite URLs and need it for flight to work.

The only part you really need is the part starting at `Flight::before`... The rest is just to test that it works.

**Comment by mikecao** [comment]
Flight now handles method overriding natively. In commit 5ba910981f8e707a0ef6f23bf14c486ae9a0f8e5.
