### ISSUE TITLE
Define path to custom class

### ISSUE THREAD

**Issue by kamov** [mikecao/flight#38]
Hi,

I just start play with flight, very nice!

I have a questions regarding routing to a specific class/method.

The code example that call Greetings class:

require 'flight/Flight.php';
Flight::route('/', array('Greetings','hello'));
Flight::start();

work fine only if Greetings.php class is on the root.
How to move this into a subfolder and setup the path?

The same when register a new class.
How to put this into a folder example Library, and then register this class?

Thanks

**Comment by qlimax86** [comment]
You might look at this method:

``` PHP
Flight::path('/your/class/path');
```

**Comment by kamov** [comment]
So simple!
Big thanks!
