### ISSUE TITLE
Request use file_get_contents

### ISSUE THREAD

**Issue by kamov** [mikecao/flight#40]
Hi,

I see that Request class use file_get_contents function.

This is disable on my server for security reason.

On line 53 there is:

'body' => file_get_contents('php://input')

Can you replace this with cURL example:

``` php

function file_get_contents_curl($url) {
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_AUTOREFERER, TRUE);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);       

    $data = curl_exec($ch);
    curl_close($ch);

    return $data;
}

```

**Comment by philo23** [comment]
I'm fairly certain this wouldn't fix your problem, php://input is a wrapper to access stdin using the standard file handling functions like readfile(), file() and file_get_contents(). The curl extension as far as I'm aware has no support for this.

You might be able to get around the restrictions on your server using some of the information displayed here: http://php.net/manual/en/wrappers.php.php (eg: $HTTP_RAW_POST_DATA) but even so I doubt this will be added into Flight.

**Comment by kamov** [comment]
Hi,

thanks for info.

Currently I am working on localhost, where allow_fopen is enabled.
But I am worry regarding when I upload on my server.

But in this case is not an external link, right? 

On my server is disabled only for external link.

It's first time that I see this method. I will check into link that you kindly provide.

Thanks

**Comment by kafene** [comment]
Chances are on such a limited server you are never going to be doing request methods other than GET and POST so I would just comment that line out or not worry about it, it will always be empty.

Also if this _is_ actually disabled by `allow_url_fopen` I'd report that to PHP.net as a bug, since even though it has a URL format, it is not a URL, it's an internal PHP resource.

**Comment by kamov** [comment]
Thank you Kafene.

I will go to close this as solved. 

Best regards
