### ISSUE TITLE
Need "splat" or similar for wildcard match

### ISSUE THREAD

**Issue by jamiekurtz** [mikecao/flight#43]
If I have a route like  'GET /api/content/*', and someone submits a URL like '/api/content/home/about', I want to be able to get the 'home/about' part in an function argument. It might work like this:

Flight::route('GET /api/content/*', function($wildcard) {
    echo $wildcard;
});

The Ruby REST library Sinatra allows this: 

get '/say/_/to/_' do
  # matches /say/hello/to/world
  params[:splat] # => ["hello", "world"]
end

get '/download/_._' do
  # matches /download/path/to/file.xml
  params[:splat] # => ["path/to/file", "xml"]
end

**Comment by jamiekurtz** [comment]
Here's a function I created to do something similar in my own code:

function getWildcardPath($s, $start) {
    $parts = explode("/", $s);
    $path_parts = array_slice($parts, $start);
    return implode("/", $path_parts);
}

**Comment by neico** [comment]
I got this to work via named parameters:

the regex looks like this: 'GET /api/content/@Path:*'

this doesn't work by default.
You need to remove the / on line https://github.com/mikecao/flight/blob/master/flight/net/Route.php#L72 for it to match the entire path and not just until the next /

Maybe this can be turned into a proper feature without breaking stuff (which I'm sure will happen if you just use it like that :/)

**Comment by mikecao** [comment]
The matching route is now passed in as the last parameter to your callback function so you can get the splat info:

``` php
Flight::route('/@name/@id', function($name, $id, $route){
   echo $route->splat;
});
```

Available in commit 7817255a61304c7419f08d137499145ff942c7f7.

**Comment by ozh** [comment]
That's interesting. It should be mentioned in the doc. You should have the doc as a separate branch to allow contributions on it :)

**Comment by julianxhokaxhiu** [comment]
I think that this is not true anymore. I'm trying using any type of patterns but no route parameter as the last one given.

Probably a bug?

**Comment by mikecao** [comment]
@julianxhokaxhiu what do you see when you do this?

``` php
Flight::route('/', function(){
  var_dump(func_get_args());
});
```

**Comment by julianxhokaxhiu** [comment]
<pre>
array (size=0)
  empty
</pre>

I've patched your code anyway and I've created a pull request ( https://github.com/mikecao/flight/pull/117 ) you can see if it's good but actually, it works.

**Comment by mikecao** [comment]
I don't have any problems when I run it. This is what I get with the above code:

``` php
array (size=1)
  0 => 
    object(flight\net\Route)[7]
      public 'pattern' => string '/' (length=1)
      public 'callback' => 
        object(Closure)[1]
      public 'methods' => 
        array (size=1)
          0 => string '*' (length=1)
      public 'params' => 
        array (size=0)
          empty
      public 'regex' => null
      public 'splat' => null
```

Also, your patch won't work because you are setting a param called route when it should be a property. If the user declared a @route param you would be overwriting it.

**Comment by julianxhokaxhiu** [comment]
Oh ok, strange fact. I'm using WAMP Server 2.5 64 bit ( http://www.wampserver.com/en/ ) and I've installed your Framework through Composer.

What I'm getting using your code is that result (empty array).

Try on your environment this

``` php
Flight::route('/*', function() {
  var_dump(func_get_args());
});
```

and tell me what you get because I always get an empty array too.

Are you sure your code is synced with this one on GitHub? Also I'm fixing my code using the native <code>array_push</code> function.

**Comment by mikecao** [comment]
Are you using the dev-master from composer? What version number do you see in the VERSION file?

And your fix is still not right. You shouldn't touch the params array since that is reserved for named parameters only.

**Comment by julianxhokaxhiu** [comment]
I'm using the v1.1 from Composer, not the dev-master. Shoud I use that?

Actually I'm using the <code>*</code> selector in composer to get the latest version available (which brings me the 1.1).

You should push new versions if there are available...I thought it was the latest one ( https://packagist.org/packages/mikecao/flight )

**Comment by mikecao** [comment]
Yes, you should be using dev-master to get all the latest changes. 1.1 is the last stable version. At some point I will push out another version.

**Comment by julianxhokaxhiu** [comment]
Thank you then, you can close this issue if you want :)

Also, you should update the docs to reflect this. Keep up with this awesome framework!
