### ISSUE TITLE
Flight::request()->data based on content type

### ISSUE THREAD

**Issue by slashmili** [mikecao/flight#45]
Hi there,

Have you ever considered to map Flight::request()->data key values based on request Content-Type.

This feature is useful in RESTful APIs, it adds an abstraction in Flight::request()->data and developer no needs to worry about the content-type of request

```
POST /api/user HTTP/1.1
Accept: application/json
Content-type: application/json
Content-Length: 10

{"id":100}
```

``` php
$request = \flight\net\Request ();
$request->data[id] == 100;
```

or maybe with new class

``` php
$request = \flight\net\RestRequest ();
$request->data[id] == 100;
```

I know that extending flight is so easy but I was wondering if you want to add it to flight's repo not.

**Comment by centipod** [comment]
And, in working with PHP, there are other incoming POST data sets that seem not to work with Flight..

I have updated my copy of the Request object with the below method to ensure $this->data contains ALL post data:

```
/**
 * Custom data collect function
 */
private function getData() {

    // Get post stream first
    $post = array();
    parse_str(file_get_contents('php://input'), $post);

    // Then add POST data
    foreach ($_POST as $key=>$value) {
        $post[$key] = $value;
    }

    return $post;
}
```

And in the constructor:

'data' => new Collection($this->getData()),

**Comment by kamov** [comment]
@ChristianSchuit I have already all data from POST using  $this->data

**Comment by centipod** [comment]
Guys, I keep getting stuck on this and a similar problem. Both my "data" on POST and my "query" on GET remain empty..?

When dumping the Flight::request() response, I have the following. You can see the params in the URL and the empty query. Am I doing something wrong here?

```
"url": "/categories?psize=10",
"base": "/solutions/MiioMobile",
"method": "GET",
"referrer": "",
"ip": "10.0.2.2",
"ajax": false,
"scheme": "HTTP/1.1",
"user_agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0",
"body": "",
"type": "",
"length": 0,
"query": {},
"data": {},
"cookies": {},
"files": {},
"secure": false,
"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
"proxy_ip": ""
```

Calling the URL directly from my Firefox browser..

**Comment by centipod** [comment]
Anyone?

**Comment by mateuszgachowski** [comment]
Whats your .htaccess and what server?

**Comment by centipod** [comment]
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]

Apache HTTP server with PHP 5.3.3

**Comment by rizqyhi** [comment]
hi,
any news on this? i've got the similar problem. fyi, i'm calling it via ajax.

**Comment by mikecao** [comment]
@ChristianSchuit can you do a var_dump of the $_GET and $_POST as well?

**Comment by mateuszgachowski** [comment]
@ChristianSchuit and maybe the request dump (Request Headers and Response, from e.g. Chrome Web Developer Tools)

**Comment by davidbielik** [comment]
For anyone experiencing a similar issue, something like this might help (before Flight's code) in index.php:

```
try{
    $_POST = (array) json_decode(urldecode(file_get_contents("php://input")));
}catch(Exception $e){
}
```
