### ISSUE TITLE
404 Error out the box

### ISSUE THREAD

**Issue by egnwd** [mikecao/flight#48]
I just downloaded flight and then accessed it via localhost `http://localhost:8888/E/Elliot%20Greenwood/Web/prototype/` & I received a 404 Not Found Error (from Flight not the Server). 

I've added the following .htaccess:
     **RewriteEngine On
     RewriteCond %{REQUEST_FILENAME} !-f
     RewriteCond %{REQUEST_FILENAME} !-d
     RewriteRule ^(.*)$ index.php [QSA,L]**

my httpd.conf has got `AllowOverride All` in it.

`Flight::request()->base` returns **/E/Elliot Greenwood/Web/prototype** & `Flight::request()->url` returns **/E/Elliot%20Greenwood/Web/prototype/**

All of the code as it was when I downloaded it, should I have changed something? The readme file says to create the index.php file but the download included it with the code already in there. I'm not sure what is going on.

Thanks,
    Elliot

**Comment by mikecao** [comment]
It probably has something to do with the space in between "Elliot" and "Greenwood". I'll try and reproduce it and provide a fix.

**Comment by egnwd** [comment]
Ahh thanks for the tip, changing this line:

`'base' => str_replace('\\', '/', dirname(getenv('SCRIPT_NAME'))),`

to this:

`'base' => str_replace(" ", "%20", str_replace('\\', '/', dirname(getenv('SCRIPT_NAME')))),`

in the Request.php file fixed my bug no sure what happens with other punctuation marks, there's probably a more fool-proof  fix

**Comment by mateuszgachowski** [comment]
I think that its better to use str_replace with an array:
'base' => str_replace(array(' ', '\'), array('%20', '/'),
dirname(getenv('SCRIPT_NAME)))

If more replacements will be necessary it will be much easier to add them.

Kind Regards,

2013/8/7 elliotgreenwood notifications@github.com

**Comment by egnwd** [comment]
Ahh, thanks!
