### ISSUE TITLE
$this in anonymous function

### ISSUE THREAD

**Issue by fabiandev** [mikecao/flight#50]
It is not possible to use $this from anonymous function before PHP 5.4.0.
I just ran into that problem.
Changing it in Engine.php on line 90 will make flight compatible with PHP 5.3 again:

``` php
$self = $this;
$this->loader->register('view', '\flight\template\View', array(), function($view) use($self) {
    $view->path = $self->get('flight.views.path');
});
```

**Comment by mikecao** [comment]
Thanks! Now fixed in b4a9d6f70eef2bb09c757afe662f02d55691894f.
