### ISSUE TITLE
lastModified and etag return worng headers

### ISSUE THREAD

**Issue by raxell** [mikecao/flight#51]
_lastModified() and _etag() use the _halt method for returning a 304 response, but the _halt method clear the cache by calling ->cache(false) on the response.
In this way the 304 response remain for 1 request and on the next a 200 response is sent instead of the 304.
You should modify with something like this:

``` php
    public function _lastModified($time) {
        $this->response()->header('Last-Modified', date(DATE_RFC1123, $time));

        if ($time === strtotime(getenv('HTTP_IF_MODIFIED_SINCE'))) {
            header('Last-Modified: ' . gmdate('D, d M Y H:i:s', $time) . ' GMT', true, 304);
        }
    }
```

**Comment by mikecao** [comment]
Thanks! Now fixed in b4a9d6f70eef2bb09c757afe662f02d55691894f.
