### ISSUE TITLE
Filter "before" route method

### ISSUE THREAD

**Issue by chapani** [mikecao/flight#54]
Hi,

I'd like to check for HTTP method (get/post/delete/put/patch) and check for authentication. I thought this would work:

``` php
Flight::before('route', function(&$params, &$output){
    // check for a method
});
```

but it doesn't work. Any suggestions?

thanks,
-- buriwoy

**Comment by mikecao** [comment]
Your code is saying you want your function to run before the `route` method. So it will check for authentication every time you try to add a route, which is probably not what you want. Instead you should do it before the `start` method.

**Comment by chapani** [comment]
thanks!

**Comment by chapani** [comment]
@mikecao 
Maybe I'm missing something, but this code does nothing:

``` php
Flight::before('start', function(&$params, &$output) {
  var_dump($params);
});
```

**Comment by mikecao** [comment]
That's because `Flight::start()` is called without any parameters. Did you actually call the start method?

**Comment by chapani** [comment]
I cleared parameters, but no success. This doesn't output anything:

``` php
Flight::before('start', function() {
  print "Please, work!";
});
```

I need to check a request method and if it is not GET, then I need to authenticate the request. Can I achieve this with filtering? Or, do I need to check it in each route callback function?

**Comment by chapani** [comment]
Yes, this is the last line in my file:

``` php
Flight::start();
```

**Comment by mikecao** [comment]
I think it's because all output before start is discarded. In your route callbacks you may have to manipulate the response headers, so any output before that would raise errors. But your before method should be running. There are other ways you check, like throwing an exception in the before filter.

**Comment by mikecao** [comment]
I'm going to work on a fix so that pre-start output doesn't get discarded.

**Comment by chapani** [comment]
Thanks, that'd be very helpful!
