### ISSUE TITLE
500 Internal Server Error for routes

### ISSUE THREAD

**Issue by kamov** [mikecao/flight#58]
Hi,

after upgrade to phpfox 5.5.3 I got 500 error for this simple route:

Flight::route('/member(/@page)', array('Member','browse'), $page);

The error is caused by $page which is not defined

500 Internal Server Error
Undefined variable: page (8)
#0 C:\WebServer2\htdocs\test\app\routes.php(21): Flight::handleError(8, 'Undefined varia...', 'C:\WebServer2\h...', 21, Array)
#1 C:\WebServer2\htdocs\test\app\bootstrap.php(38): require_once('C:\WebServer2\h...')
#2 C:\WebServer2\htdocs\test\index.php(15): require_once('C:\WebServer2\h...')
#3 {main}

**Comment by mikecao** [comment]
There is no third parameter for the route method. Your callback function should accept $page as a parameter.

**Comment by kamov** [comment]
@mikecao I don't understand what you mean...

The route work fine with php 5.3, but with 5.5.3 there is 500 error

**Comment by mikecao** [comment]
The error is that the $page variable is undefined. When you upgraded, your configuration probably changed to strict mode so undefined variables are considered errors.

Even so, the route method doesn't take a third parameter. Your callback, array('Member','browse'), should be accepting the parameter. For example

``` php
class Member {
  function browse($page) {
    // Do something
  }
}
```

**Comment by kamov** [comment]
Hi,
thanks for your reply.

Yes, my class Member method browse accept parameter $page

> > When you upgraded, your configuration probably changed to strict mode so undefined variables are considered errors.

I got your point. So for avoid this, I should define var $page before use it? In this case strict mode will also work. I will check if mode is strict, I just upgrade xampp.

All the best
