### ISSUE TITLE
Custom HTTP status with stop() or json()

### ISSUE THREAD

**Issue by ghost** [mikecao/flight#59]
Although it is not custom to have content with some of the HTTP status codes, many developers do return error messages and status information. It would be very useful to be able to use the Flight::json(..) with both content AND a status code. Same goes for the Flight::stop(..) function.

When simply adding these params to the methods, a strange behavior occurs. At some point the Request::status(..) methods is calls with an array as parameter..? I have worked around this, but it would be good if you could include this in the framework.

Thanks :)

**Comment by mikecao** [comment]
Now fixed in commit 6fe4e32feefeed44984bba93d4657e9d111f8556.
