### ISSUE TITLE
got header

### ISSUE THREAD

**Issue by MarcoStagno** [mikecao/flight#61]
how could be possibile to get all http request headers (custom headers too)?

**Comment by mikecao** [comment]
You'll have to parse the global $_SERVER variable and get the headers. The Request object only contains a small subset of available request data.

**Comment by philo23** [comment]
It's not really Flight specific, but couldn't you use `get_headers()`?

**Comment by MarcoStagno** [comment]
thanks for your replies.. I was asking to know if there were something else to use ..
