### ISSUE TITLE
Support for error reporting

### ISSUE THREAD

**Issue by Ecaz** [mikecao/flight#63]
Why does parse errors not work with Flight? Include Flight and start it then place some random gibberish inside a route (or anywhere else) and the script just dies.

Suggestion, display errors and then die.

Even with error reporting E_ALL and display_errors on it behaves in the same way.

**Comment by mikecao** [comment]
I just tested the latest version and parse errors display fine. I've tried introducing a syntax error in the main script as well as in an include and they both display errors.
