### ISSUE TITLE
Methods for making database connections and querying databases

### ISSUE THREAD

**Issue by HiggsOfChaos** [mikecao/flight#64]
Hello,

Newbie question here?

How can I make a connection to a database and make CRUD operations using flight methods?

It would be convenient to have flight retrieve values from tables and such.

Thanks

**Comment by sah-comp** [comment]
I recommend https://github.com/gabordemooij/redbean

**Comment by kafene** [comment]
This is really beyond the scope of Flight... though you might notice mike maintains another repo which is a SQL tool: https://github.com/mikecao/sparrow

The best advice I can give you for using a database with flight is to use `register` to set up a PDO instance for each connection you need. I do it like this:

``` php
Flight::register(
    'db', # <= will be available as Flight::db()
    'PDO',
    # Arguments passed with the object is instantiated:
    [
        'sqlite:'. __DIR__ .'/whatever.db',
        null,
        null,
        [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        ]
    ],
    # Callback function run after its first instantiated
    function ($db) {
        $db->exec(
            "CREATE TABLE IF NOT EXISTS blah (
                id INTEGER PRIMARY KEY,
                username TEXT,
                password TEXT
            )"
        );
    }
);
```
