### ISSUE TITLE
Extend Flight with Plugin / Hook

### ISSUE THREAD

**Issue by kamov** [mikecao/flight#65]
There is a way with Flight for use plugin/hook?

THanks

**Comment by mikecao** [comment]
You can use the before/after methods to hook to any event.

**Comment by kamov** [comment]
Thanks!
I found example only for function.

How to use filters before after with a custom class method?

**Comment by kamov** [comment]
Hi @mikecao 

I understand that is possible use before/after only for mapped method using "map"

Right?

If I want add filters for a Class Method?

For example I have class method User::login()
which is called via route:

Flight::route('/login(/@msg)', array('User','login'), $msg);

I try do this but not work:

``` php
// Map a custom method
Flight::map('login', function($msg){ 
    User::login($msg);
});


Flight::after('login', function(&$params, &$output){
    $output .= $output . ' filtered';
});
```

and new route:

``` php

Flight::route('/login(/@msg)', function($msg){
    Flight::login($msg);
});

```

**Comment by mikecao** [comment]
The $output you're manipulating is the output of the function you're mapping. Your function is not returning anything. You'll want to do something like this:

``` php
$output = Flight::login($msg);
```

**Comment by kamov** [comment]
Thank you for tip ! 

So I can only filter method mapped by method "map"

I can't filter my own class method...shame.
