### ISSUE TITLE
htaccess public folder

### ISSUE THREAD

**Issue by nikmauro** [mikecao/flight#67]
My directory structure is the following:

public/
    index.php
    .htaccess 
     vendor/flight
.htaccess

The .htaccess in the root folder looks like this:
<IfModule mod_rewrite.c>
   RewriteEngine on
   RewriteRule ^$ public/    [L]
   RewriteRule (.*) public/$1 [L]
</IfModule>

The .htaccess in the public folder looks like this:
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]

my url with .htaccess is http://localhost/myapp/index.php

my url without htaccess is http://localhost/myapp/public/index.php

all working fine but the flight not working.

**Comment by mikecao** [comment]
What do you mean by not working? What do you see?

**Comment by Maxoos** [comment]
if you are using a Mac you should add this in the beginning of the file:
RewriteBase /~username/folder
