### ISSUE TITLE
Polluting the Namespace

### ISSUE THREAD

**Issue by eric1234** [mikecao/flight#71]
I'm interested in polluting the namespace. I know where supposed to be good and properly namespace stuff. But for simple flight apps it just clutters stuff up. I come from the sinatra world where you have beautiful stuff like:

```
get '/path' do
  json my_data
end
```

So the following just seems crazy:

```
Flight::route('/path', function() {
  Flight::json(my_data());
});
```

Now most of this hot mess comes from PHP being so verbose. But I'm wondering if the Flight clutter could be removed. I'm thinking something like:

```
Flight::pollute();

route('/path', function() {
  json(my_data());
});
```

So the app would specifically request Flight to pollute. That would create bring route, json, etc into the global scope. Obviously this doesn't scale for big apps. But many Flight apps aren't meant to be big. Removing all the `Flight::` prefixes makes the code more readable. Obviously someone who pollutes takes the risk of not working in namespaces.

My current workaround is to alias `Flight` as `_`. So:

```
use Flight as _;

_::route('/ping', function() {
  _::json(array('version' => '1'));
});
```

It's not bad but not having the `_::` would be even better. Should I submit a pull request or would you rather not encourage this sort of behavior. :)

**Comment by ozh** [comment]
Not a project member & just a user, but I'd be interested in seeing how you would implement that `pollute()` :)

**Comment by eric1234** [comment]
Well things like "route" and "start" I would just define the methods in the global namespace to proxy off to the Flight functions. Ideally methods like json could be defined in some sort of namespace and when the callable is run we put the execution of that callable in the same namespace. This would reduce the pollution while still giving the convenience. Just unsure if I can actually do that in PHP or if I'll have to put those type of methods in the global space also.

But before I dove into the implementation I figured I would see if there is any desire for functionality like that or if I should just stick to my `_` hack.

**Comment by mikecao** [comment]
I don't think I would ever implement a pollute method into the framework itself since it would be cumbersome to deal with function name collisions without diving into the code. I would just create a `global.php` file that defines your functions in the global namespace which proxy to the Flight methods. Then you can just include that file whenever needed and it would be much easier to modify.

**Comment by eric1234** [comment]
K, thanks for the feedback. That's why I wanted to float the idea by you before implementing.
