### ISSUE TITLE
Regular Expressions Match

### ISSUE THREAD

**Issue by blackstrip** [mikecao/flight#72]
I need match validated IP address.
so i find this regexp: \b((2[0-5]{2}|1[0-9]{2}|[0-9]{1,2}).){3}(2[0-5]{2}|1[0-9]{2}|[0-9]{1,2})\b
how to route it?

follow can't work! 
Flight::route('/search/@ip:(\b((2[0-5]{2}|1[0-9]{2}|[0-9]{1,2}).){3}(2[0-5]{2}|1[0-9]{2}|[0-9]{1,2})\b)', function($ip)

**Comment by mikecao** [comment]
You should avoid doing complex regular expressions in the route. You can do it this way instead, which should yield much better performance:

``` php
Flight::route('/search/@ip', function($ip){
  if (filter_var($ip, FILTER_VALIDATE_IP)) {
    // valid
  } else {
    // not valid
  }
});
```

**Comment by blackstrip** [comment]
ok, thanks, nice work! :+1:
