### ISSUE TITLE
load controller class 

### ISSUE THREAD

**Issue by Stephan123** [mikecao/flight#74]
Hello!

I want to perform a routing.
The URL is: http://flight//front/controller/start/index

I want to perform a routing controller to 'start' and the method 'index'. How can I do this with Flight :: route (); achieve?

Can I name the controller after PSR0?
(http://www.sitepoint.com/autoloading-and-the-psr-0-standard/)

For example: Front_Controller_Index.

Sincerely yours

Stephan

**Comment by Stephan123** [comment]
My first test.
https://github.com/Stephan123/flight

**Comment by mikecao** [comment]
You can do something like this to act as a controller:

``` php
Flight::map('controller', function($name, $action = 'index', $args = array()) {
    if (class_exists($name)) {
        $controller = new $name();
        $controller->$action();
    }
    else {
        echo "Not Found: (name: $name, action: $action)";
    }
});

Flight::route('/@name(/@action)', function($name, $action){
    if (empty($action)) $action = 'index';
    Flight::controller($name,$action);
});

Flight::route('/', function(){
    Flight::controller('home','index');
});
```

You would then use `Flight::path()` to set a directory for autoloading your controller classes.

**Comment by Stephan123** [comment]
Hello!

Thanks for the information.
I will test the micro framework further.
Currently I'm looking for a way that the template engine 'twig' to use as view.
(http://twig.sensiolabs.org/)

Which database class do you recommend?

I wish you and your family a Merry Christmas.

Sincerely yours

Stephan Krauss

**Comment by int3rlop3r** [comment]
Checkout Issue #64
