### ISSUE TITLE
Middleware support

### ISSUE THREAD

**Issue by norman784** [mikecao/flight#76]
Seems that there is no support for middlewares, just like [expressjs](https://github.com/visionmedia/express) does, so will be much easier to add some checks before the main action is called.

**Comment by mikecao** [comment]
Flight doesn't have a strict request/response model like other apps so it doesn't really use middleware. Though this could be done a future enhancement. Currently, everything that can be done with middleware can be done with the `before` and `after` methods.

**Comment by norman784** [comment]
thanks..

**Comment by n0nag0n** [comment]
This is being added in #514 in case you're still interested.
