### ISSUE TITLE
Routing logic looks inaccurate

### ISSUE THREAD

**Issue by yanilkr** [mikecao/flight#77]
Here are my routes
Flight::route("GET /v1.0/123", function(){
    echo 'v1.0/123 route' ;
});

Flight::route("GET /123", function(){
    echo '123 route'  ;
});

and I hit the server with 

server/v1.0/123 and the expected behavior is to see 'v1.0/123 route'
but we always get the other

This is a very common pattern e.g
usecase 1
/api/1.0/users
/api/2.0/users

usecase 2
/api/users
/api/usa/users

All these routes have to match to different routes.
http://server/

**Comment by mikecao** [comment]
Can you try with the latest commit? I just ran a test with your example and it works fine.

**Comment by ozh** [comment]
For the record I'm using 5414b90 from Oct 30 2013 and I cannot reproduce this.

**Comment by yanilkr** [comment]
Iam using latest from main branch here is the latest commit

git log --format="%H" | head -n1
777ac096ec4a7e7c8551b33588ee675cb8bf8046

it does not work on the same.

**Comment by mikecao** [comment]
Are those your only two routes? Remember that the order you define the route matters. The ones defined first will be matched first. Other than that, I can't reproduce the problem.

Alternatively you can use named parameters and do additional processing in your callback.

``` php
Flight::route('/@api/@version', function($api,$version){
  // Process route
});
```

**Comment by yanilkr** [comment]
I was evaluating the framework, I downloaded it, setup apache and changed the index.php file to this. The named parameters works ok.

<?php

require 'flight/Flight.php';

Flight::route("GET /123", function(){
    echo '123 route'  ;
});

Flight::route("GET /v1.0/123", function(){
    echo 'v1.0/123 route' ;
});

Flight::start();

**Comment by yanilkr** [comment]
Verified, This is not a Flight framework issue.

I had a vhost file where flight is part of a sub directory

From documentation the rewrite rule is as below.
RewriteRule ^(.*)$ index.php [QSA,L]

I changed it to 
RewriteRule ^(.*)$ index.php/$1 [QSA,L]

and then the routes started working fine.
