### ISSUE TITLE
Automagically including all dependent route classes

### ISSUE THREAD

**Issue by nodesocket** [mikecao/flight#78]
First, amazing piece of software. :smile_cat: Using it for the API for https://commando.io.

What is the best practice when routing like:

```
Flight::route('GET /', array("Root", "_get"));
```

Then defining a file `/routes/Root.php` with:

```
class Root {
    public static function _get() {
        echo "hello from Root::_get()";
    }
}
```

To include all php files **automagically** in the directory `routes`? Is this functionality built into Flight, or should we do something like:

```
spl_autoload_register(function($class_name)  {
    require_once("routes/" . $class_name . ".php");
});
```

Thanks.

**Comment by mikecao** [comment]
You can use `Flight::path()` to add a directory where classes will be autoloaded.

Additionally you can use named parameters to get more control on the loading process:

``` php
Flight::route("/@class(/@method)", function($class, $method){
  // Do something
});
```

**Comment by nodesocket** [comment]
Thanks, worked like a champ.
