### ISSUE TITLE
Route method not allowed

### ISSUE THREAD

**Issue by nodesocket** [mikecao/flight#79]
If I have a route (only `GET`):

```
Flight::route('GET /', array("Root", "_get"));
```

And I try:

```
curl https://api.mydomain.com -X POST
```

The response is:

```
HTTP/1.1 404 Not Found
Server: nginx
Date: Sat, 04 Jan 2014 00:39:53 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding

<h1>404 Not Found</h1><h3>The page you have requested could not be found.</h3>
```

Really though this should return http status code `405 - Method Not Allowed` with a header:

```
 Allow: GET
```

What is the best way to implement this?

**Comment by nodesocket** [comment]
By the way @mikecao would love to meetup and chat since you're here in San Francisco. Send us an e-mail, its on our website https://commando.io.

**Comment by mikecao** [comment]
You're right that sending a 405 is the probably the correct way to handle it, and I thought about building it in natively. However, you are allowed to define multiple routes with different methods, but the same url:

``` php
Flight::route('GET /', function(){
  // Handle gets
});

Flight::route('POST /', function(){
  // Handle posts
});
```

So, to handle that the framework would need to process every single route, then compare the matching ones against the request method. This would add a lot of processing overhead, especially if there are a lot of defined routes or complex regexes are involved. Right now, it just checks the method first, and if there is no match it just jumps to the next route. Much faster.

Still, you could do something like this:

``` php
// Match all methods
Flight::route('/', function(){
  // Check the request method
  if (Flight::request()->method != 'GET') {
    Flight::response(false)
      ->status(405)
      ->header('Allow', 'GET')
      ->send();
  }

  // Continue processing
});
```

**Comment by nodesocket** [comment]
Could we maybe build a utility function like:

```
public static function enforceMethods(array $allowedMethods) {
    if(!in_array(Flight::request()->method, $allowedMethods) {
         Flight::response(false)
                ->status(405)
                ->header('Allow',  implode(", ", $allowedMethods))
                ->send();
    }
}
```

**Comment by nodesocket** [comment]
Doing the method check inside my route class did not work:

```
Flight::route('GET /', array("Root", "_get"));

class Root {
    public static function _get() {
        if (Flight::request()->method !== 'GET') {
            Flight::response(false)
                    ->status(405)
                    ->header('Allow', 'GET')
                    ->send();
        }

        Flight::json(array(
            "version" => "v1"
        ));
    }
}
```

**Comment by mikecao** [comment]
You can map your utility method using the `map` method and then have it run before the start method:

``` php
Flight::before('start', function(){
  Flight::enforceMethods(array('GET'));
});
```

In your second example your route is `GET /`, meaning only match GET requests. Then you are checking if it's not GET, which is impossible.

**Comment by nodesocket** [comment]
Makes sense on the custom utility function.

Sorry, I'm an idiot on the second example.
