### ISSUE TITLE
Using a custom response, blows away headers being set with nginx

### ISSUE THREAD

**Issue by nodesocket** [mikecao/flight#81]
I am setting custom headers in nginx in the `location` block. I.E.

```
add_header X-Foo "Bar";
```

If I do:

```
Flight::response()
          ->status(405)
          ->send();
```

The header `X-Foo` is removed from the response. However, simply doing:

```
Flight::json();
```

Works, the header `X-Foo` still exists.

**Comment by mikecao** [comment]
From the nginx docs, http://wiki.nginx.org/HttpHeadersModule

`Adds headers to the HTTP response when the response code is equal to 200, 204, 301, 302 or 304.`

**Comment by nodesocket** [comment]
I'll be damned. Interesting. Ok, I guess I can re-add the headers with Flight.
