### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by blackstrip** [mikecao/flight#83]
Hi Team,
conn_config.php:
$db_user        = 'balabala';
$db_pass        = 'balabala';
$db_database    = 'temps'; 

index.php:
require 'framework/flight/Flight.php';
require 'framework/conn_config.php';
Flight::route('/hello/', function(){
    echo "hello";
    echo $db_database;
});
Flight::start();

I got this message:
500 Internal Server Error
Undefined variable: db_database (8)

How can i use this variables?

**Comment by mateuszgachowski** [comment]
You can try:

``` php
$db_config = array(
 'user' => 'blablabla',
 'pass' => 'blablabla',
 'database' => 'temps'
);
Flight::route('/hello/', function() use ($db_config) {
  var_dump($db_config); 
});
```

If you want to read more about how callbacks work, go [Here](http://www.php.net/manual/en/functions.anonymous.php)

**Comment by blackstrip** [comment]
Hi mateuszgachowski, it's worked. thx!
If i have some xxx_class.php need to use those variables, can i use "use ($db_config)" too?

**Comment by mateuszgachowski** [comment]
Everything about using anonymous functions with classes and more you can find in the link I have provided :)

Hope it helps.

Regards,
Mateusz

**Comment by blackstrip** [comment]
Cool, thx Buddy, i'm newbie. :p
