### ISSUE TITLE
Route pre hook

### ISSUE THREAD

**Issue by nodesocket** [mikecao/flight#84]
Is there a way to have a hook called before routes? For example I have:

```
Flight::route('/foo', array("Root", "foo"));
Flight::route('/bar', array("Root", "bar"));
Flight::route('/car', array("Root", "car"));
```

Then the class Root:

```
class Root {
    public static function foo() {
    }

    public static function bar() {
    }

    public static function car() {
    }
}
```

I want to execute some logic before `foo`, `bar`, and `car` without copying and pasting the logic three times. Is this possible?

**Comment by mikecao** [comment]
The start method is when all the routes get processed, so just add a hook before it.

``` php
Flight::before('start', function(){
  // Always run before any route
});
```

Note however that it will run even if no routes are matched. Alternatively, you can map your own passthrough method:

``` php
Flight::map('controller', function(){
   // Routes all requests
});
```

Then add a hook to that:

``` php
Flight::before('controller', function(){
  // Runs only when controller is invoked
});
```

**Comment by nodesocket** [comment]
With `Flight::before('start', ...` is there a way I can see the route hooked methods, i.e:

```
Flight::before('start', function($methods) {
    //GET, POST
    echo implode(', ', $methods);
}
```

**Comment by mikecao** [comment]
Your callback function is passed the matching route as the last parameter. So you can do something like this:

``` php
Flight::route('GET|POST /', function($route){
  echo implode(',', $route->methods);
});
```

**Comment by nodesocket** [comment]
I need to get the route methods in the `Flight::before()` hook, not inside the actual route function. Does that make sense?

**Comment by mikecao** [comment]
You would have to loop through all the routes in the router and check them yourself, though I don't understand what purpose that would serve.

``` php
$routes = Flight::router()->getRoutes();

foreach ($routes as $route) {
  // Check $route->methods
}
```

**Comment by nodesocket** [comment]
Basically, in the `Flight::before()` hook I connect to MySQL, however, before I do this, I want to check the route method. Does that make sense?

**Comment by mikecao** [comment]
Before the framework starts none of the routes have been processed, so all you're getting are the methods that you yourself have assigned to the routes. So I don't really get the point of getting that data. The route passed to the callback is the route that was actually matched.

Also, you should just map your MySQL connection to a method, like `Flight::db()`, so the connection will only be made when invoked.

**Comment by kafene** [comment]
To comment on the original post:

> Is there a way to have a hook called before routes? For example I have:
> Flight::route('/foo', array("Root", "foo"));
> Flight::route('/bar', array("Root", "bar"));
> Flight::route('/car', array("Root", "car"));

Kind of, here is what I would suggest:

``` php
Flight::map('rootFoo', ['Root', 'foo']);
Flight::map('rootBar', ['Root', 'bar']);
Flight::map('rootCar', ['Root', 'car']);
```

Since those are attached to flight now you can use before and after hooks on them:

``` php
$callback = ['SomeClass', 'someMethod'];
Flight::before('rootFoo', $callback);
Flight::before('rootBar', $callback);
Flight::before('rootCar', $callback);
```

And then route these methods instead of the original, so the framework will handle each one:

``` php
Flight::route('/foo', ['Flight', 'rootFoo']);
Flight::route('/bar', ['Flight', 'rootBar']);
Flight::route('/car', ['Flight', 'rootCar']);
```

I am pretty certain that this will work as you intend.

For a large number of routes, it might be worthwhile to define everything in an array which you can loop over to do the mapping, applying of before/after hooks, and routing them in one swoop, and then access that array when you need the details of how each method has been/will be used before the response is sent.
