### ISSUE TITLE
flight and composer

### ISSUE THREAD

**Issue by Stephan123** [mikecao/flight#86]
Hello!

I want to use 'flight' as a basic framework.
In this framework I want to use other classes.
These classes are added to the Php Composer.
The compser shall, in the 'vendor' these classes.
Under 'vendor' is the autoload.php from the Php Composer.

If the autoloader of 'flight' embed the autoload.php of the Composer?

Sincerely yours

Stephan

**Comment by mikecao** [comment]
Flight's autoload and composer's autoload are different things. You can load Flight through composer and not worry about running the autoload manually.

**Comment by Stephan123** [comment]
Hello!

Thanks for the reply.
I guess I should like to see the 'routing' again.
Thank you for the wonderful framework.

Sincerely yours

Stephan
