### ISSUE TITLE
autoloader and namespace

### ISSUE THREAD

**Issue by Stephan123** [mikecao/flight#91]
Hallo !

Ich habe eine Anfängerfrage.
Unterstützt 'flight' die Verwendung von 'namespace' ?

Mit freundlichen Grüßen

Stephan

**Comment by sah-comp** [comment]
Stephan wanted to know if Flight does support namespaces and i would say yes. If you take a look at the code in https://github.com/mikecao/flight/blob/master/flight/core/Loader.php (Line 168) you'll see how the requested class name is treated with str_replace.

**Comment by Stephan123** [comment]
Hello! 

I think 'flight' can not use namespace. 
A simple experiment. 

## Set in a 'controller' a namespace.

namespace controller;

class controller_namespace {

```
public function __construct(){

}

public function index()
{
    echo 'Controller: namespace, Action: index';
}
```

## }

I get an error message. 
Fatal error: Class 'controller_namespace' not found in C:\xampp\htdocs\flight\flight\core\Loader.php on line 116

Sincerely yours 

Stephan

**Comment by sah-comp** [comment]
Pretend we have a index.php that might look like this:

```
<?php
require './flight/flight/Flight.php';
Flight::set('flight.log_errors', true);
Flight::path(__DIR__ . '/src');
Flight::route('/test', function() {
    $c = new Controller\Foo();
    $c->bar();
});
Flight::start();
?>
```

and your class Foo is in src/controller/foo.php looking like following it works:

```
<?php
namespace Controller;

class Foo {
    public function __construct()
    {
    }

    public function bar()
    {
        echo 'Foo::bar()';
    }
}
?>
```
