### ISSUE TITLE
Autoloading Problem

### ISSUE THREAD

**Issue by mithataydogmus** [mikecao/flight#93]
Hello,

I read and applied past issues about autoloading but in my app i can't load my classes and can't use them in index.php. My system and index.php looks like this;
- Greeting Class is in examples on Flight. Hello() function returns "hello world".
- "sys" directory is the main directory which stores all kind of libraries,frameworks,views etc.
- In root directory of server there are "index.php" and "sys".
- There is a "config.php" in my "sys/conf/" directory. So inside of config.php for testing purposes there is a "Greeting class".

And this is my index.php on root.

// Import Libraries
require 'sys/flight/Flight.php';
// To autoload classes
Flight::path('/sys/conf/');
// Register loaded classes
Flight::register('test','Greeting');
// Main Routing Part
Flight::route('/', function() {
    $newclass = Flight::test();
    $newclass->hello();
});
Flight::start();

Flight is working normally but when i tried to use Flight::test() after that i can't even use echo inside route(). So my app is blocked somehow after using registered class.

Where am i doing wrong ?

Edit: (Using Aptana and MAMP(PHP 5.5.3)).

**Comment by mikecao** [comment]
Flight does not autoload every file it finds in a directory. When you specify `/sys/conf/` as a autoload directory, it's looking a specific file that represents the class. So if you're doing:

``` php
Flight::register('test', 'Greeting');
```

Then it is looking for a file `/sys/conf/Greeting.php`. What's the error you're getting?

**Comment by mithataydogmus** [comment]
I found the problem with debugging in autoload source code. My flight framework inside of "sys" directory. I need to use "**DIR**" for path() function. 

So when i did this it worked:

Flight::path(**DIR**."sys/conf/");

Why the normal way don't work for me i really don't know.

Thanks anyway.
