### ISSUE TITLE
Path() Problem

### ISSUE THREAD

**Issue by mithataydogmus** [mikecao/flight#94]
Hello,

I figured how framework working now but when i debug the code i found weird stuff. When i checked autoloading classes section i found following loading scheme.

/Applications/MAMP/htdocs/test/sys/flight/Engine.php
/Applications/MAMP/htdocs/test/sys/flight/core/Dispatcher.php
/Applications/MAMP/htdocs/test/sys/flight/net/Router.php
/Applications/MAMP/htdocs/test/sys/flight/net/Route.php
/Applications/MAMP/htdocs/test/sys/flight/net/Request.php
/Applications/MAMP/htdocs/test/sys/flight/util/Collection.php
/Applications/MAMP/htdocs/test/sys/flight/net/Response.php
/Applications/MAMP/htdocs/test/sys/Accounts.php
/Applications/MAMP/htdocs/test/sys/conf/Accounts.php

path(__ DIR __.'/sys/conf')

I don't understand this part, why Flight always looking "sys/Accounts.php" too ? It always happening like this. It tries to load unavailable file all the time, "sys/conf/" is my path and my class is there. (sys/conf/Accounts.php is the right one)

Is it a problem or is there reasonable explanation for this ?

Thank you.

**Comment by mikecao** [comment]
The `path` method **adds** a location for autoloading, it is not a single location. So you could do this:

``` php
Flight::path('/dir1');
Flight::path('/dir2');
Flight::path('/dir3');
```

And the autoloader will check all the defined locations in order. By default it registers the location of the flight folder as an autoload path, otherwise none of the Flight classes would load.
