### ISSUE TITLE
Sample authentication with filter

### ISSUE THREAD

**Issue by gmoisio** [mikecao/flight#97]
Hi all, trying flight framework, I was looking at a way to athenticate a user and its rights before some routes rendering.
I was trying "before" which looks like an answer, but there is something that I don't understand.

Suppose this simple route:

Flight::route('GET /', function(){
  Flight::render('index.php');
});

Something like:

Flight::before('index', function(&$params, &$output){
*****_-something_to_do-**_***
});

looks to not be the right way.... but how to name the function associated with the route without an external function... I tried some syntax without any success!
In addition, I tried to use class/method with the route and the before has no action on the method used in the route... Is the filters only applied on map?

Thanks

**Comment by mikecao** [comment]
The before and after filter only work on Flight methods, not methods for any class. So you have to first map a method using `Flight::map` then run a filter on it.

**Comment by gmoisio** [comment]
Hi, thanks and what is the syntax to map a method bellonging to a class?

Flight::route('GET /', array('Pages','index'));

class Pages {
  public static function index() {
    Flight::render('index.php');
  }
}

In the documentation, I don't find information on that case.
Regards

**Comment by mikecao** [comment]
You can use any callback. So, you can do

``` php
Flight::map('test', array('Pages','index'));

Flight::route('GET /', function(){
  Flight::test();
});
```

**Comment by gmoisio** [comment]
Thanks, it works and I better understand the way to use Flight...
