### ISSUE TITLE
Multilinguage environment

### ISSUE THREAD

**Issue by gmoisio** [mikecao/flight#98]
Hi all, in a multilingual process, I want to load an external file contening an array of the strings and pass it to the method that will render the right page.

Something like (lang.php includes an array $text):

require 'lang.pgp';

Flight::route('GET /', array('Pages','index'));

class Pages {
  public static function index() {
    Flight::render('index.php', $text);
  }
}

I have some difficulties to pass $text from side to side without using global..... Is there a specific syntax with Flight or may I use singleton (can register help for this)?
Thanks

**Comment by mikecao** [comment]
The render method just takes an array for template data. You can use global arrays, singletons, map a method; however you want to provide that data is up to you.

**Comment by gmoisio** [comment]
Ok thanks
